/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  BookmarksApi,
  ComplianceApi,
  DirectMessagesApi,
  GeneralApi,
  ListsApi,
  SpacesApi,
  TweetsApi,
  UsersApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { XCustom } from "./client-custom";

export class X extends XCustom {
  readonly bookmarks: BookmarksApi;
  readonly compliance: ComplianceApi;
  readonly directMessages: DirectMessagesApi;
  readonly general: GeneralApi;
  readonly lists: ListsApi;
  readonly spaces: SpacesApi;
  readonly tweets: TweetsApi;
  readonly users: UsersApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.bookmarks = new BookmarksApi(configuration);
    this.compliance = new ComplianceApi(configuration);
    this.directMessages = new DirectMessagesApi(configuration);
    this.general = new GeneralApi(configuration);
    this.lists = new ListsApi(configuration);
    this.spaces = new SpacesApi(configuration);
    this.tweets = new TweetsApi(configuration);
    this.users = new UsersApi(configuration);
  }

}
