/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddRulesRequest } from './add-rules-request';
import { DeleteRulesRequest } from './delete-rules-request';
import { DeleteRulesRequestDelete } from './delete-rules-request-delete';
import { RuleNoId } from './rule-no-id';

/**
 * @type AddOrDeleteRulesRequest
 * @export
 */
export type AddOrDeleteRulesRequest = AddRulesRequest | DeleteRulesRequest;


