/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Problem } from './problem';
import { Rule } from './rule';
import { RulesResponseMetadata } from './rules-response-metadata';

/**
 * A response from modifying user-specified stream filtering rules.
 * @export
 * @interface AddOrDeleteRulesResponse
 */
export interface AddOrDeleteRulesResponse {
    /**
     * All user-specified stream filtering rules that were created.
     * @type {Array<Rule>}
     * @memberof AddOrDeleteRulesResponse
     */
    'data'?: Array<Rule>;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof AddOrDeleteRulesResponse
     */
    'errors'?: Array<Problem>;
    /**
     * 
     * @type {RulesResponseMetadata}
     * @memberof AddOrDeleteRulesResponse
     */
    'meta': RulesResponseMetadata;
}

