/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RuleNoId } from './rule-no-id';

/**
 * A request to add a user-specified stream filtering rule.
 * @export
 * @interface AddRulesRequest
 */
export interface AddRulesRequest {
    /**
     * 
     * @type {Array<RuleNoId>}
     * @memberof AddRulesRequest
     */
    'add': Array<RuleNoId>;
}

