/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Variant } from './variant';

/**
 * 
 * @export
 * @interface AnimatedGifAllOf
 */
export interface AnimatedGifAllOf {
    /**
     * 
     * @type {string}
     * @memberof AnimatedGifAllOf
     */
    'preview_image_url'?: string;
    /**
     * An array of all available variants of the media.
     * @type {Array<Variant>}
     * @memberof AnimatedGifAllOf
     */
    'variants'?: Array<Variant>;
}

