/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AnimatedGifAllOf } from './animated-gif-all-of';
import { Media } from './media';
import { Variant } from './variant';

/**
 * @type AnimatedGif
 * @export
 */
export type AnimatedGif = AnimatedGifAllOf & Media;


