/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BlockUserMutationResponseData } from './block-user-mutation-response-data';
import { Problem } from './problem';

/**
 * 
 * @export
 * @interface BlockUserMutationResponse
 */
export interface BlockUserMutationResponse {
    /**
     * 
     * @type {BlockUserMutationResponseData}
     * @memberof BlockUserMutationResponse
     */
    'data'?: BlockUserMutationResponseData;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof BlockUserMutationResponse
     */
    'errors'?: Array<Problem>;
}

