/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BookmarkMutationResponseData } from './bookmark-mutation-response-data';
import { Problem } from './problem';

/**
 * 
 * @export
 * @interface BookmarkMutationResponse
 */
export interface BookmarkMutationResponse {
    /**
     * 
     * @type {BookmarkMutationResponseData}
     * @memberof BookmarkMutationResponse
     */
    'data'?: BookmarkMutationResponseData;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof BookmarkMutationResponse
     */
    'errors'?: Array<Problem>;
}

