/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ClientForbiddenProblemAllOf
 */
export interface ClientForbiddenProblemAllOf {
    /**
     * 
     * @type {string}
     * @memberof ClientForbiddenProblemAllOf
     */
    'reason'?: ClientForbiddenProblemAllOfReasonEnum;
    /**
     * 
     * @type {string}
     * @memberof ClientForbiddenProblemAllOf
     */
    'registration_url'?: string;
}

type ClientForbiddenProblemAllOfReasonEnum = 'official-client-forbidden' | 'client-not-enrolled'


