/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ClientForbiddenProblemAllOf } from './client-forbidden-problem-all-of';
import { Problem } from './problem';

/**
 * @type ClientForbiddenProblem
 * A problem that indicates your client is forbidden from making this request.
 * @export
 */
export type ClientForbiddenProblem = ClientForbiddenProblemAllOf & Problem;


