/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ComplianceJobStatus } from './compliance-job-status';
import { ComplianceJobType } from './compliance-job-type';

/**
 * 
 * @export
 * @interface ComplianceJob
 */
export interface ComplianceJob {
    /**
     * Creation time of the compliance job.
     * @type {string}
     * @memberof ComplianceJob
     */
    'created_at': string;
    /**
     * Expiration time of the download URL.
     * @type {string}
     * @memberof ComplianceJob
     */
    'download_expires_at': string;
    /**
     * URL from which the user will retrieve their compliance results.
     * @type {string}
     * @memberof ComplianceJob
     */
    'download_url': string;
    /**
     * Compliance Job ID.
     * @type {string}
     * @memberof ComplianceJob
     */
    'id': string;
    /**
     * User-provided name for a compliance job.
     * @type {string}
     * @memberof ComplianceJob
     */
    'name'?: string;
    /**
     * Status of a compliance job.
     * @type {ComplianceJobStatus}
     * @memberof ComplianceJob
     */
    'status': ComplianceJobStatus;
    /**
     * Type of compliance job to list.
     * @type {ComplianceJobType}
     * @memberof ComplianceJob
     */
    'type': ComplianceJobType;
    /**
     * Expiration time of the upload URL.
     * @type {string}
     * @memberof ComplianceJob
     */
    'upload_expires_at': string;
    /**
     * URL to which the user will upload their Tweet or user IDs.
     * @type {string}
     * @memberof ComplianceJob
     */
    'upload_url': string;
}

