/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConnectionExceptionProblemAllOf } from './connection-exception-problem-all-of';
import { Problem } from './problem';

/**
 * @type ConnectionExceptionProblem
 * A problem that indicates something is wrong with the connection.
 * @export
 */
export type ConnectionExceptionProblem = ConnectionExceptionProblemAllOf & Problem;


