/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ConnectionExceptionProblemAllOf
 */
export interface ConnectionExceptionProblemAllOf {
    /**
     * 
     * @type {string}
     * @memberof ConnectionExceptionProblemAllOf
     */
    'connection_issue'?: ConnectionExceptionProblemAllOfConnectionIssueEnum;
}

type ConnectionExceptionProblemAllOfConnectionIssueEnum = 'TooManyConnections' | 'ProvisioningSubscription' | 'RuleConfigurationIssue' | 'RulesInvalidIssue'


