/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Represents the data for the context annotation entity.
 * @export
 * @interface ContextAnnotationEntityFields
 */
export interface ContextAnnotationEntityFields {
    /**
     * Description of the context annotation entity.
     * @type {string}
     * @memberof ContextAnnotationEntityFields
     */
    'description'?: string;
    /**
     * The unique id for a context annotation entity.
     * @type {string}
     * @memberof ContextAnnotationEntityFields
     */
    'id': string;
    /**
     * Name of the context annotation entity.
     * @type {string}
     * @memberof ContextAnnotationEntityFields
     */
    'name'?: string;
}

