/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ContextAnnotationDomainFields } from './context-annotation-domain-fields';
import { ContextAnnotationEntityFields } from './context-annotation-entity-fields';

/**
 * Annotation inferred from the Tweet text.
 * @export
 * @interface ContextAnnotation
 */
export interface ContextAnnotation {
    /**
     * 
     * @type {ContextAnnotationDomainFields}
     * @memberof ContextAnnotation
     */
    'domain': ContextAnnotationDomainFields;
    /**
     * 
     * @type {ContextAnnotationEntityFields}
     * @memberof ContextAnnotation
     */
    'entity': ContextAnnotationEntityFields;
}

