/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Represents the data for the context annotation domain.
 * @export
 * @interface ContextAnnotationDomainFields
 */
export interface ContextAnnotationDomainFields {
    /**
     * Description of the context annotation domain.
     * @type {string}
     * @memberof ContextAnnotationDomainFields
     */
    'description'?: string;
    /**
     * The unique id for a context annotation domain.
     * @type {string}
     * @memberof ContextAnnotationDomainFields
     */
    'id': string;
    /**
     * Name of the context annotation domain.
     * @type {string}
     * @memberof ContextAnnotationDomainFields
     */
    'name'?: string;
}

