/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CreateAttachmentsMessageRequest } from './create-attachments-message-request';
import { CreateTextMessageRequest } from './create-text-message-request';
import { DmMediaAttachment } from './dm-media-attachment';

/**
 * @type CreateMessageRequest
 * @export
 */
export type CreateMessageRequest = CreateTextMessageRequest | CreateAttachmentsMessageRequest;


