/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A request to create a new batch compliance job.
 * @export
 * @interface CreateComplianceJobRequest
 */
export interface CreateComplianceJobRequest {
    /**
     * User-provided name for a compliance job.
     * @type {string}
     * @memberof CreateComplianceJobRequest
     */
    'name'?: string;
    /**
     * If true, this endpoint will return a pre-signed URL with resumable uploads enabled.
     * @type {boolean}
     * @memberof CreateComplianceJobRequest
     */
    'resumable'?: boolean;
    /**
     * Type of compliance job to list.
     * @type {string}
     * @memberof CreateComplianceJobRequest
     */
    'type': CreateComplianceJobRequestTypeEnum;
}

type CreateComplianceJobRequestTypeEnum = 'tweets' | 'users'


