/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DmMediaAttachment } from './dm-media-attachment';

/**
 * 
 * @export
 * @interface CreateTextMessageRequest
 */
export interface CreateTextMessageRequest {
    /**
     * Attachments to a DM Event.
     * @type {Array<DmMediaAttachment>}
     * @memberof CreateTextMessageRequest
     */
    'attachments'?: Array<DmMediaAttachment>;
    /**
     * Text of the message.
     * @type {string}
     * @memberof CreateTextMessageRequest
     */
    'text': string;
}

