/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CreateDmEventResponseData
 */
export interface CreateDmEventResponseData {
    /**
     * Unique identifier of a DM conversation. This can either be a numeric string, or a pair of numeric strings separated by a \'-\' character in the case of one-on-one DM Conversations.
     * @type {string}
     * @memberof CreateDmEventResponseData
     */
    'dm_conversation_id': string;
    /**
     * Unique identifier of a DM Event.
     * @type {string}
     * @memberof CreateDmEventResponseData
     */
    'dm_event_id': string;
}

