/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CreateMessageRequest } from './create-message-request';

/**
 * 
 * @export
 * @interface CreateDmConversationRequest
 */
export interface CreateDmConversationRequest {
    /**
     * The conversation type that is being created.
     * @type {string}
     * @memberof CreateDmConversationRequest
     */
    'conversation_type': CreateDmConversationRequestConversationTypeEnum;
    /**
     * 
     * @type {CreateMessageRequest}
     * @memberof CreateDmConversationRequest
     */
    'message': CreateMessageRequest;
    /**
     * Participants for the DM Conversation.
     * @type {Array<string>}
     * @memberof CreateDmConversationRequest
     */
    'participant_ids': Array<string>;
}

type CreateDmConversationRequestConversationTypeEnum = 'Group'


