/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DmMediaAttachment } from './dm-media-attachment';

/**
 * 
 * @export
 * @interface CreateAttachmentsMessageRequest
 */
export interface CreateAttachmentsMessageRequest {
    /**
     * Attachments to a DM Event.
     * @type {Array<DmMediaAttachment>}
     * @memberof CreateAttachmentsMessageRequest
     */
    'attachments': Array<DmMediaAttachment>;
    /**
     * Text of the message.
     * @type {string}
     * @memberof CreateAttachmentsMessageRequest
     */
    'text'?: string;
}

