/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CreateDmEventResponseData } from './create-dm-event-response-data';
import { Problem } from './problem';

/**
 * 
 * @export
 * @interface CreateDmEventResponse
 */
export interface CreateDmEventResponse {
    /**
     * 
     * @type {CreateDmEventResponseData}
     * @memberof CreateDmEventResponse
     */
    'data'?: CreateDmEventResponseData;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof CreateDmEventResponse
     */
    'errors'?: Array<Problem>;
}

