/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * IDs and values of all deleted user-specified stream filtering rules.
 * @export
 * @interface DeleteRulesRequestDelete
 */
export interface DeleteRulesRequestDelete {
    /**
     * IDs of all deleted user-specified stream filtering rules.
     * @type {Array<string>}
     * @memberof DeleteRulesRequestDelete
     */
    'ids'?: Array<string>;
    /**
     * Values of all deleted user-specified stream filtering rules.
     * @type {Array<string>}
     * @memberof DeleteRulesRequestDelete
     */
    'values'?: Array<string>;
}

