/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DeleteRulesRequestDelete } from './delete-rules-request-delete';

/**
 * A response from deleting user-specified stream filtering rules.
 * @export
 * @interface DeleteRulesRequest
 */
export interface DeleteRulesRequest {
    /**
     * 
     * @type {DeleteRulesRequestDelete}
     * @memberof DeleteRulesRequest
     */
    'delete': DeleteRulesRequestDelete;
}

