/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DisallowedResourceProblemAllOf } from './disallowed-resource-problem-all-of';
import { Problem } from './problem';

/**
 * @type DisallowedResourceProblem
 * A problem that indicates that the resource requested violates the precepts of this API.
 * @export
 */
export type DisallowedResourceProblem = DisallowedResourceProblemAllOf & Problem;


