/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DisallowedResourceProblemAllOf
 */
export interface DisallowedResourceProblemAllOf {
    /**
     * 
     * @type {string}
     * @memberof DisallowedResourceProblemAllOf
     */
    'resource_id': string;
    /**
     * 
     * @type {string}
     * @memberof DisallowedResourceProblemAllOf
     */
    'resource_type': DisallowedResourceProblemAllOfResourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof DisallowedResourceProblemAllOf
     */
    'section': DisallowedResourceProblemAllOfSectionEnum;
}

type DisallowedResourceProblemAllOfResourceTypeEnum = 'user' | 'tweet' | 'media' | 'list' | 'space'
type DisallowedResourceProblemAllOfSectionEnum = 'data' | 'includes'


