/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DmEventAttachments } from './dm-event-attachments';
import { DmEventReferencedTweetsInner } from './dm-event-referenced-tweets-inner';

/**
 * 
 * @export
 * @interface DmEvent
 */
export interface DmEvent {
    /**
     * 
     * @type {DmEventAttachments}
     * @memberof DmEvent
     */
    'attachments'?: DmEventAttachments;
    /**
     * 
     * @type {string}
     * @memberof DmEvent
     */
    'created_at'?: string;
    /**
     * Unique identifier of a DM conversation. This can either be a numeric string, or a pair of numeric strings separated by a \'-\' character in the case of one-on-one DM Conversations.
     * @type {string}
     * @memberof DmEvent
     */
    'dm_conversation_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof DmEvent
     */
    'event_type': string;
    /**
     * Unique identifier of a DM Event.
     * @type {string}
     * @memberof DmEvent
     */
    'id': string;
    /**
     * A list of participants for a ParticipantsJoin or ParticipantsLeave event_type.
     * @type {Array<string>}
     * @memberof DmEvent
     */
    'participant_ids'?: Array<string>;
    /**
     * A list of Tweets this DM refers to.
     * @type {Array<DmEventReferencedTweetsInner>}
     * @memberof DmEvent
     */
    'referenced_tweets'?: Array<DmEventReferencedTweetsInner>;
    /**
     * Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
     * @type {string}
     * @memberof DmEvent
     */
    'sender_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof DmEvent
     */
    'text'?: string;
}

