/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DmMediaAttachment
 */
export interface DmMediaAttachment {
    /**
     * The unique identifier of this Media.
     * @type {string}
     * @memberof DmMediaAttachment
     */
    'media_id': string;
}

