/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DuplicateRuleProblemAllOf } from './duplicate-rule-problem-all-of';
import { Problem } from './problem';

/**
 * @type DuplicateRuleProblem
 * The rule you have submitted is a duplicate.
 * @export
 */
export type DuplicateRuleProblem = DuplicateRuleProblemAllOf & Problem;


