/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Media } from './media';
import { Place } from './place';
import { Poll } from './poll';
import { Topic } from './topic';
import { Tweet } from './tweet';
import { User } from './user';

/**
 * 
 * @export
 * @interface Expansions
 */
export interface Expansions {
    /**
     * 
     * @type {Array<Media>}
     * @memberof Expansions
     */
    'media'?: Array<Media>;
    /**
     * 
     * @type {Array<Place>}
     * @memberof Expansions
     */
    'places'?: Array<Place>;
    /**
     * 
     * @type {Array<Poll>}
     * @memberof Expansions
     */
    'polls'?: Array<Poll>;
    /**
     * 
     * @type {Array<Topic>}
     * @memberof Expansions
     */
    'topics'?: Array<Topic>;
    /**
     * 
     * @type {Array<Tweet>}
     * @memberof Expansions
     */
    'tweets'?: Array<Tweet>;
    /**
     * 
     * @type {Array<User>}
     * @memberof Expansions
     */
    'users'?: Array<User>;
}

