/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface FieldUnauthorizedProblemAllOf
 */
export interface FieldUnauthorizedProblemAllOf {
    /**
     * 
     * @type {string}
     * @memberof FieldUnauthorizedProblemAllOf
     */
    'field': string;
    /**
     * 
     * @type {string}
     * @memberof FieldUnauthorizedProblemAllOf
     */
    'resource_type': FieldUnauthorizedProblemAllOfResourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof FieldUnauthorizedProblemAllOf
     */
    'section': FieldUnauthorizedProblemAllOfSectionEnum;
}

type FieldUnauthorizedProblemAllOfResourceTypeEnum = 'user' | 'tweet' | 'media' | 'list' | 'space'
type FieldUnauthorizedProblemAllOfSectionEnum = 'data' | 'includes'


