/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FieldUnauthorizedProblemAllOf } from './field-unauthorized-problem-all-of';
import { Problem } from './problem';

/**
 * @type FieldUnauthorizedProblem
 * A problem that indicates that you are not allowed to see a particular field on a Tweet, User, etc.
 * @export
 */
export type FieldUnauthorizedProblem = FieldUnauthorizedProblemAllOf & Problem;


