/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface FilteredStreamingTweetResponseMatchingRulesInner
 */
export interface FilteredStreamingTweetResponseMatchingRulesInner {
    /**
     * Unique identifier of this rule.
     * @type {string}
     * @memberof FilteredStreamingTweetResponseMatchingRulesInner
     */
    'id': string;
    /**
     * A tag meant for the labeling of user provided rules.
     * @type {string}
     * @memberof FilteredStreamingTweetResponseMatchingRulesInner
     */
    'tag'?: string;
}

