/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EntityIndicesInclusiveInclusive } from './entity-indices-inclusive-inclusive';
import { FullTextEntitiesAnnotationsInnerAllOf } from './full-text-entities-annotations-inner-all-of';

/**
 * @type FullTextEntitiesAnnotationsInner
 * Annotation for entities based on the Tweet text.
 * @export
 */
export type FullTextEntitiesAnnotationsInner = EntityIndicesInclusiveInclusive & FullTextEntitiesAnnotationsInnerAllOf;


