/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DmEvent } from './dm-event';
import { Expansions } from './expansions';
import { Get2DmConversationsIdDmEventsResponseMeta } from './get2-dm-conversations-id-dm-events-response-meta';
import { Problem } from './problem';

/**
 * 
 * @export
 * @interface Get2DmConversationsWithParticipantIdDmEventsResponse
 */
export interface Get2DmConversationsWithParticipantIdDmEventsResponse {
    /**
     * 
     * @type {Array<DmEvent>}
     * @memberof Get2DmConversationsWithParticipantIdDmEventsResponse
     */
    'data'?: Array<DmEvent>;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof Get2DmConversationsWithParticipantIdDmEventsResponse
     */
    'errors'?: Array<Problem>;
    /**
     * 
     * @type {Expansions}
     * @memberof Get2DmConversationsWithParticipantIdDmEventsResponse
     */
    'includes'?: Expansions;
    /**
     * 
     * @type {Get2DmConversationsIdDmEventsResponseMeta}
     * @memberof Get2DmConversationsWithParticipantIdDmEventsResponse
     */
    'meta'?: Get2DmConversationsIdDmEventsResponseMeta;
}

