/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Get2TweetsCountsAllResponseMeta } from './get2-tweets-counts-all-response-meta';
import { Problem } from './problem';
import { SearchCount } from './search-count';

/**
 * 
 * @export
 * @interface Get2TweetsCountsRecentResponse
 */
export interface Get2TweetsCountsRecentResponse {
    /**
     * 
     * @type {Array<SearchCount>}
     * @memberof Get2TweetsCountsRecentResponse
     */
    'data'?: Array<SearchCount>;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof Get2TweetsCountsRecentResponse
     */
    'errors'?: Array<Problem>;
    /**
     * 
     * @type {Get2TweetsCountsAllResponseMeta}
     * @memberof Get2TweetsCountsRecentResponse
     */
    'meta'?: Get2TweetsCountsAllResponseMeta;
}

