/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Expansions } from './expansions';
import { Get2ComplianceJobsResponseMeta } from './get2-compliance-jobs-response-meta';
import { List } from './list';
import { Problem } from './problem';

/**
 * 
 * @export
 * @interface Get2UsersIdPinnedListsResponse
 */
export interface Get2UsersIdPinnedListsResponse {
    /**
     * 
     * @type {Array<List>}
     * @memberof Get2UsersIdPinnedListsResponse
     */
    'data'?: Array<List>;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof Get2UsersIdPinnedListsResponse
     */
    'errors'?: Array<Problem>;
    /**
     * 
     * @type {Expansions}
     * @memberof Get2UsersIdPinnedListsResponse
     */
    'includes'?: Expansions;
    /**
     * 
     * @type {Get2ComplianceJobsResponseMeta}
     * @memberof Get2UsersIdPinnedListsResponse
     */
    'meta'?: Get2ComplianceJobsResponseMeta;
}

