/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Expansions } from './expansions';
import { Get2DmConversationsIdDmEventsResponseMeta } from './get2-dm-conversations-id-dm-events-response-meta';
import { List } from './list';
import { Problem } from './problem';

/**
 * 
 * @export
 * @interface Get2UsersIdListMembershipsResponse
 */
export interface Get2UsersIdListMembershipsResponse {
    /**
     * 
     * @type {Array<List>}
     * @memberof Get2UsersIdListMembershipsResponse
     */
    'data'?: Array<List>;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof Get2UsersIdListMembershipsResponse
     */
    'errors'?: Array<Problem>;
    /**
     * 
     * @type {Expansions}
     * @memberof Get2UsersIdListMembershipsResponse
     */
    'includes'?: Expansions;
    /**
     * 
     * @type {Get2DmConversationsIdDmEventsResponseMeta}
     * @memberof Get2UsersIdListMembershipsResponse
     */
    'meta'?: Get2DmConversationsIdDmEventsResponseMeta;
}

