/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Expansions } from './expansions';
import { Get2TweetsIdQuoteTweetsResponseMeta } from './get2-tweets-id-quote-tweets-response-meta';
import { Problem } from './problem';
import { Tweet } from './tweet';

/**
 * 
 * @export
 * @interface Get2TweetsIdQuoteTweetsResponse
 */
export interface Get2TweetsIdQuoteTweetsResponse {
    /**
     * 
     * @type {Array<Tweet>}
     * @memberof Get2TweetsIdQuoteTweetsResponse
     */
    'data'?: Array<Tweet>;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof Get2TweetsIdQuoteTweetsResponse
     */
    'errors'?: Array<Problem>;
    /**
     * 
     * @type {Expansions}
     * @memberof Get2TweetsIdQuoteTweetsResponse
     */
    'includes'?: Expansions;
    /**
     * 
     * @type {Get2TweetsIdQuoteTweetsResponseMeta}
     * @memberof Get2TweetsIdQuoteTweetsResponse
     */
    'meta'?: Get2TweetsIdQuoteTweetsResponseMeta;
}

