/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ComplianceJob } from './compliance-job';
import { Get2ComplianceJobsResponseMeta } from './get2-compliance-jobs-response-meta';
import { Problem } from './problem';

/**
 * 
 * @export
 * @interface Get2ComplianceJobsResponse
 */
export interface Get2ComplianceJobsResponse {
    /**
     * 
     * @type {Array<ComplianceJob>}
     * @memberof Get2ComplianceJobsResponse
     */
    'data'?: Array<ComplianceJob>;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof Get2ComplianceJobsResponse
     */
    'errors'?: Array<Problem>;
    /**
     * 
     * @type {Get2ComplianceJobsResponseMeta}
     * @memberof Get2ComplianceJobsResponse
     */
    'meta'?: Get2ComplianceJobsResponseMeta;
}

