/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Get2ComplianceJobsResponseMeta
 */
export interface Get2ComplianceJobsResponseMeta {
    /**
     * The number of results returned in this response.
     * @type {number}
     * @memberof Get2ComplianceJobsResponseMeta
     */
    'result_count'?: number;
}

