/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Get2TweetsCountsAllResponseMeta
 */
export interface Get2TweetsCountsAllResponseMeta {
    /**
     * The newest id in this response.
     * @type {string}
     * @memberof Get2TweetsCountsAllResponseMeta
     */
    'newest_id'?: string;
    /**
     * The next token.
     * @type {string}
     * @memberof Get2TweetsCountsAllResponseMeta
     */
    'next_token'?: string;
    /**
     * The oldest id in this response.
     * @type {string}
     * @memberof Get2TweetsCountsAllResponseMeta
     */
    'oldest_id'?: string;
    /**
     * The sum of results returned in this response.
     * @type {number}
     * @memberof Get2TweetsCountsAllResponseMeta
     */
    'total_tweet_count'?: number;
}

