/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Expansions } from './expansions';
import { Get2TweetsSearchAllResponseMeta } from './get2-tweets-search-all-response-meta';
import { Problem } from './problem';
import { Tweet } from './tweet';

/**
 * 
 * @export
 * @interface Get2TweetsSearchAllResponse
 */
export interface Get2TweetsSearchAllResponse {
    /**
     * 
     * @type {Array<Tweet>}
     * @memberof Get2TweetsSearchAllResponse
     */
    'data'?: Array<Tweet>;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof Get2TweetsSearchAllResponse
     */
    'errors'?: Array<Problem>;
    /**
     * 
     * @type {Expansions}
     * @memberof Get2TweetsSearchAllResponse
     */
    'includes'?: Expansions;
    /**
     * 
     * @type {Get2TweetsSearchAllResponseMeta}
     * @memberof Get2TweetsSearchAllResponse
     */
    'meta'?: Get2TweetsSearchAllResponseMeta;
}

