/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Expansions } from './expansions';
import { Problem } from './problem';
import { User } from './user';

/**
 * 
 * @export
 * @interface Get2UsersByResponse
 */
export interface Get2UsersByResponse {
    /**
     * 
     * @type {Array<User>}
     * @memberof Get2UsersByResponse
     */
    'data'?: Array<User>;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof Get2UsersByResponse
     */
    'errors'?: Array<Problem>;
    /**
     * 
     * @type {Expansions}
     * @memberof Get2UsersByResponse
     */
    'includes'?: Expansions;
}

