/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Expansions } from './expansions';
import { Problem } from './problem';
import { Tweet } from './tweet';

/**
 * 
 * @export
 * @interface Get2TweetsSearchStreamResponse
 */
export interface Get2TweetsSearchStreamResponse {
    /**
     * 
     * @type {Tweet}
     * @memberof Get2TweetsSearchStreamResponse
     */
    'data'?: Tweet;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof Get2TweetsSearchStreamResponse
     */
    'errors'?: Array<Problem>;
    /**
     * 
     * @type {Expansions}
     * @memberof Get2TweetsSearchStreamResponse
     */
    'includes'?: Expansions;
}

