/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface InvalidRequestProblemAllOfErrors
 */
export interface InvalidRequestProblemAllOfErrors {
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof InvalidRequestProblemAllOfErrors
     */
    'parameters'?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {string}
     * @memberof InvalidRequestProblemAllOfErrors
     */
    'message'?: string;
}

