/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InvalidRequestProblemAllOf } from './invalid-request-problem-all-of';
import { InvalidRequestProblemAllOfErrors } from './invalid-request-problem-all-of-errors';
import { Problem } from './problem';

/**
 * @type InvalidRequestProblem
 * A problem that indicates this request is invalid.
 * @export
 */
export type InvalidRequestProblem = InvalidRequestProblemAllOf & Problem;


