/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ListCreateRequest
 */
export interface ListCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof ListCreateRequest
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof ListCreateRequest
     */
    'name': string;
    /**
     * 
     * @type {boolean}
     * @memberof ListCreateRequest
     */
    'private'?: boolean;
}

