/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A Twitter List is a curated group of accounts.
 * @export
 * @interface ListCreateResponseData
 */
export interface ListCreateResponseData {
    /**
     * The unique identifier of this List.
     * @type {string}
     * @memberof ListCreateResponseData
     */
    'id': string;
    /**
     * The name of this List.
     * @type {string}
     * @memberof ListCreateResponseData
     */
    'name': string;
}

