/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ListPinnedResponseData } from './list-pinned-response-data';
import { Problem } from './problem';

/**
 * 
 * @export
 * @interface ListPinnedResponse
 */
export interface ListPinnedResponse {
    /**
     * 
     * @type {ListPinnedResponseData}
     * @memberof ListPinnedResponse
     */
    'data'?: ListPinnedResponseData;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof ListPinnedResponse
     */
    'errors'?: Array<Problem>;
}

