/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A Twitter List is a curated group of accounts.
 * @export
 * @interface List
 */
export interface List {
    /**
     * 
     * @type {string}
     * @memberof List
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof List
     */
    'created_at'?: string;
    /**
     * 
     * @type {number}
     * @memberof List
     */
    'follower_count'?: number;
    /**
     * The unique identifier of this List.
     * @type {string}
     * @memberof List
     */
    'id': string;
    /**
     * 
     * @type {number}
     * @memberof List
     */
    'member_count'?: number;
    /**
     * The name of this List.
     * @type {string}
     * @memberof List
     */
    'name': string;
    /**
     * Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
     * @type {string}
     * @memberof List
     */
    'owner_id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof List
     */
    'private'?: boolean;
}

