/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ListDeleteResponseData } from './list-delete-response-data';
import { Problem } from './problem';

/**
 * 
 * @export
 * @interface ListDeleteResponse
 */
export interface ListDeleteResponse {
    /**
     * 
     * @type {ListDeleteResponseData}
     * @memberof ListDeleteResponse
     */
    'data'?: ListDeleteResponseData;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof ListDeleteResponse
     */
    'errors'?: Array<Problem>;
}

