/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ListMutateResponseData } from './list-mutate-response-data';
import { Problem } from './problem';

/**
 * 
 * @export
 * @interface ListMutateResponse
 */
export interface ListMutateResponse {
    /**
     * 
     * @type {ListMutateResponseData}
     * @memberof ListMutateResponse
     */
    'data'?: ListMutateResponseData;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof ListMutateResponse
     */
    'errors'?: Array<Problem>;
}

