/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Media
 */
export interface Media {
    /**
     * The height of the media in pixels.
     * @type {number}
     * @memberof Media
     */
    'height'?: number;
    /**
     * The Media Key identifier for this attachment.
     * @type {string}
     * @memberof Media
     */
    'media_key'?: string;
    /**
     * 
     * @type {string}
     * @memberof Media
     */
    'type': string;
    /**
     * The width of the media in pixels.
     * @type {number}
     * @memberof Media
     */
    'width'?: number;
}

