/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface OperationalDisconnectProblemAllOf
 */
export interface OperationalDisconnectProblemAllOf {
    /**
     * 
     * @type {string}
     * @memberof OperationalDisconnectProblemAllOf
     */
    'disconnect_type'?: OperationalDisconnectProblemAllOfDisconnectTypeEnum;
}

type OperationalDisconnectProblemAllOfDisconnectTypeEnum = 'OperationalDisconnect' | 'UpstreamOperationalDisconnect' | 'ForceDisconnect' | 'UpstreamUncleanDisconnect' | 'SlowReader' | 'InternalError' | 'ClientApplicationStateDegraded' | 'InvalidRules'


