/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OperationalDisconnectProblemAllOf } from './operational-disconnect-problem-all-of';
import { Problem } from './problem';

/**
 * @type OperationalDisconnectProblem
 * You have been disconnected for operational reasons.
 * @export
 */
export type OperationalDisconnectProblem = OperationalDisconnectProblemAllOf & Problem;


