/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Media } from './media';
import { PhotoAllOf } from './photo-all-of';

/**
 * @type Photo
 * @export
 */
export type Photo = Media & PhotoAllOf;


