/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Geo } from './geo';
import { PlaceType } from './place-type';

/**
 * 
 * @export
 * @interface Place
 */
export interface Place {
    /**
     * 
     * @type {Array<string>}
     * @memberof Place
     */
    'contained_within'?: Array<string>;
    /**
     * The full name of the county in which this place exists.
     * @type {string}
     * @memberof Place
     */
    'country'?: string;
    /**
     * A two-letter ISO 3166-1 alpha-2 country code.
     * @type {string}
     * @memberof Place
     */
    'country_code'?: string;
    /**
     * The full name of this place.
     * @type {string}
     * @memberof Place
     */
    'full_name': string;
    /**
     * 
     * @type {Geo}
     * @memberof Place
     */
    'geo'?: Geo;
    /**
     * The identifier for this place.
     * @type {string}
     * @memberof Place
     */
    'id': string;
    /**
     * The human readable name of this place.
     * @type {string}
     * @memberof Place
     */
    'name'?: string;
    /**
     * 
     * @type {PlaceType}
     * @memberof Place
     */
    'place_type'?: PlaceType;
}

