/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A [GeoJson Point](https://tools.ietf.org/html/rfc7946#section-3.1.2) geometry object.
 * @export
 * @interface Point
 */
export interface Point {
    /**
     * A [GeoJson Position](https://tools.ietf.org/html/rfc7946#section-3.1.1) in the format `[longitude,latitude]`.
     * @type {Array<number>}
     * @memberof Point
     */
    'coordinates': Array<number>;
    /**
     * 
     * @type {string}
     * @memberof Point
     */
    'type': PointTypeEnum;
}

type PointTypeEnum = 'Point'


