/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PollOption } from './poll-option';

/**
 * Represent a Poll attached to a Tweet.
 * @export
 * @interface Poll
 */
export interface Poll {
    /**
     * 
     * @type {number}
     * @memberof Poll
     */
    'duration_minutes'?: number;
    /**
     * 
     * @type {string}
     * @memberof Poll
     */
    'end_datetime'?: string;
    /**
     * Unique identifier of this poll.
     * @type {string}
     * @memberof Poll
     */
    'id': string;
    /**
     * 
     * @type {Array<PollOption>}
     * @memberof Poll
     */
    'options': Array<PollOption>;
    /**
     * 
     * @type {string}
     * @memberof Poll
     */
    'voting_status'?: PollVotingStatusEnum;
}

type PollVotingStatusEnum = 'open' | 'closed'


