/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ResourceUnauthorizedProblemAllOf
 */
export interface ResourceUnauthorizedProblemAllOf {
    /**
     * 
     * @type {string}
     * @memberof ResourceUnauthorizedProblemAllOf
     */
    'parameter': string;
    /**
     * 
     * @type {string}
     * @memberof ResourceUnauthorizedProblemAllOf
     */
    'resource_id': string;
    /**
     * 
     * @type {string}
     * @memberof ResourceUnauthorizedProblemAllOf
     */
    'resource_type': ResourceUnauthorizedProblemAllOfResourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ResourceUnauthorizedProblemAllOf
     */
    'section': ResourceUnauthorizedProblemAllOfSectionEnum;
    /**
     * 
     * @type {string}
     * @memberof ResourceUnauthorizedProblemAllOf
     */
    'value': string;
}

type ResourceUnauthorizedProblemAllOfResourceTypeEnum = 'user' | 'tweet' | 'media' | 'list' | 'space'
type ResourceUnauthorizedProblemAllOfSectionEnum = 'data' | 'includes'


