/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Problem } from './problem';
import { ResourceNotFoundProblemAllOf } from './resource-not-found-problem-all-of';

/**
 * @type ResourceNotFoundProblem
 * A problem that indicates that a given Tweet, User, etc. does not exist.
 * @export
 */
export type ResourceNotFoundProblem = Problem & ResourceNotFoundProblemAllOf;


