/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ResourceUnavailableProblemAllOf
 */
export interface ResourceUnavailableProblemAllOf {
    /**
     * 
     * @type {string}
     * @memberof ResourceUnavailableProblemAllOf
     */
    'parameter': string;
    /**
     * 
     * @type {string}
     * @memberof ResourceUnavailableProblemAllOf
     */
    'resource_id': string;
    /**
     * 
     * @type {string}
     * @memberof ResourceUnavailableProblemAllOf
     */
    'resource_type': ResourceUnavailableProblemAllOfResourceTypeEnum;
}

type ResourceUnavailableProblemAllOfResourceTypeEnum = 'user' | 'tweet' | 'media' | 'list' | 'space'


