/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ResourceNotFoundProblemAllOf
 */
export interface ResourceNotFoundProblemAllOf {
    /**
     * 
     * @type {string}
     * @memberof ResourceNotFoundProblemAllOf
     */
    'parameter': string;
    /**
     * 
     * @type {string}
     * @memberof ResourceNotFoundProblemAllOf
     */
    'resource_id': string;
    /**
     * 
     * @type {string}
     * @memberof ResourceNotFoundProblemAllOf
     */
    'resource_type': ResourceNotFoundProblemAllOfResourceTypeEnum;
    /**
     * Value will match the schema of the field.
     * @type {string}
     * @memberof ResourceNotFoundProblemAllOf
     */
    'value': string;
}

type ResourceNotFoundProblemAllOfResourceTypeEnum = 'user' | 'tweet' | 'media' | 'list' | 'space'


