/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Problem } from './problem';
import { ResourceUnavailableProblemAllOf } from './resource-unavailable-problem-all-of';

/**
 * @type ResourceUnavailableProblem
 * A problem that indicates a particular Tweet, User, etc. is not available to you.
 * @export
 */
export type ResourceUnavailableProblem = Problem & ResourceUnavailableProblemAllOf;


