/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A user-provided stream filtering rule.
 * @export
 * @interface RuleNoId
 */
export interface RuleNoId {
    /**
     * A tag meant for the labeling of user provided rules.
     * @type {string}
     * @memberof RuleNoId
     */
    'tag'?: string;
    /**
     * The filterlang value of the rule.
     * @type {string}
     * @memberof RuleNoId
     */
    'value': string;
}

