/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A user-provided stream filtering rule.
 * @export
 * @interface Rule
 */
export interface Rule {
    /**
     * Unique identifier of this rule.
     * @type {string}
     * @memberof Rule
     */
    'id'?: string;
    /**
     * A tag meant for the labeling of user provided rules.
     * @type {string}
     * @memberof Rule
     */
    'tag'?: string;
    /**
     * The filterlang value of the rule.
     * @type {string}
     * @memberof Rule
     */
    'value': string;
}

