/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Rule } from './rule';
import { RulesResponseMetadata } from './rules-response-metadata';

/**
 * 
 * @export
 * @interface RulesLookupResponse
 */
export interface RulesLookupResponse {
    /**
     * 
     * @type {Array<Rule>}
     * @memberof RulesLookupResponse
     */
    'data'?: Array<Rule>;
    /**
     * 
     * @type {RulesResponseMetadata}
     * @memberof RulesLookupResponse
     */
    'meta': RulesResponseMetadata;
}

