/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RulesRequestSummary } from './rules-request-summary';

/**
 * 
 * @export
 * @interface RulesResponseMetadata
 */
export interface RulesResponseMetadata {
    /**
     * 
     * @type {RulesRequestSummary}
     * @memberof RulesResponseMetadata
     */
    'summary'?: RulesRequestSummary;
    /**
     * The next token.
     * @type {string}
     * @memberof RulesResponseMetadata
     */
    'next_token'?: string;
    /**
     * Number of Rules in result set.
     * @type {number}
     * @memberof RulesResponseMetadata
     */
    'result_count'?: number;
    /**
     * 
     * @type {string}
     * @memberof RulesResponseMetadata
     */
    'sent': string;
}

