/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RulesRequestSummaryOneOf } from './rules-request-summary-one-of';
import { RulesRequestSummaryOneOf1 } from './rules-request-summary-one-of1';

/**
 * @type RulesRequestSummary
 * @export
 */
export type RulesRequestSummary = RulesRequestSummaryOneOf | RulesRequestSummaryOneOf1;


