/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Represent a Search Count Result.
 * @export
 * @interface SearchCount
 */
export interface SearchCount {
    /**
     * The end time of the bucket.
     * @type {string}
     * @memberof SearchCount
     */
    'end': string;
    /**
     * The start time of the bucket.
     * @type {string}
     * @memberof SearchCount
     */
    'start': string;
    /**
     * The count for the bucket.
     * @type {number}
     * @memberof SearchCount
     */
    'tweet_count': number;
}

