/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SpaceTopicsInner } from './space-topics-inner';

/**
 * 
 * @export
 * @interface Space
 */
export interface Space {
    /**
     * The title of the Space.
     * @type {string}
     * @memberof Space
     */
    'title'?: string;
    /**
     * Creation time of the Space.
     * @type {string}
     * @memberof Space
     */
    'created_at'?: string;
    /**
     * Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
     * @type {string}
     * @memberof Space
     */
    'creator_id'?: string;
    /**
     * End time of the Space.
     * @type {string}
     * @memberof Space
     */
    'ended_at'?: string;
    /**
     * The user ids for the hosts of the Space.
     * @type {Array<string>}
     * @memberof Space
     */
    'host_ids'?: Array<string>;
    /**
     * The unique identifier of this Space.
     * @type {string}
     * @memberof Space
     */
    'id': string;
    /**
     * An array of user ids for people who were invited to a Space.
     * @type {Array<string>}
     * @memberof Space
     */
    'invited_user_ids'?: Array<string>;
    /**
     * Denotes if the Space is a ticketed Space.
     * @type {boolean}
     * @memberof Space
     */
    'is_ticketed'?: boolean;
    /**
     * The language of the Space.
     * @type {string}
     * @memberof Space
     */
    'lang'?: string;
    /**
     * The number of participants in a Space.
     * @type {number}
     * @memberof Space
     */
    'participant_count'?: number;
    /**
     * A date time stamp for when a Space is scheduled to begin.
     * @type {string}
     * @memberof Space
     */
    'scheduled_start'?: string;
    /**
     * An array of user ids for people who were speakers in a Space.
     * @type {Array<string>}
     * @memberof Space
     */
    'speaker_ids'?: Array<string>;
    /**
     * When the Space was started as a date string.
     * @type {string}
     * @memberof Space
     */
    'started_at'?: string;
    /**
     * The current state of the Space.
     * @type {string}
     * @memberof Space
     */
    'state': SpaceStateEnum;
    /**
     * The number of people who have either purchased a ticket or set a reminder for this Space.
     * @type {number}
     * @memberof Space
     */
    'subscriber_count'?: number;
    /**
     * The topics of a Space, as selected by its creator.
     * @type {Array<SpaceTopicsInner>}
     * @memberof Space
     */
    'topics'?: Array<SpaceTopicsInner>;
    /**
     * When the Space was last updated.
     * @type {string}
     * @memberof Space
     */
    'updated_at'?: string;
}

type SpaceStateEnum = 'live' | 'scheduled' | 'ended'


