/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The Twitter Topic object.
 * @export
 * @interface SpaceTopicsInner
 */
export interface SpaceTopicsInner {
    /**
     * The description of the given topic.
     * @type {string}
     * @memberof SpaceTopicsInner
     */
    'description'?: string;
    /**
     * An ID suitable for use in the REST API.
     * @type {string}
     * @memberof SpaceTopicsInner
     */
    'id': string;
    /**
     * The name of the given topic.
     * @type {string}
     * @memberof SpaceTopicsInner
     */
    'name': string;
}

