/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The topic of a Space, as selected by its creator.
 * @export
 * @interface Topic
 */
export interface Topic {
    /**
     * The description of the given topic.
     * @type {string}
     * @memberof Topic
     */
    'description'?: string;
    /**
     * Unique identifier of this Topic.
     * @type {string}
     * @memberof Topic
     */
    'id': string;
    /**
     * The name of the given topic.
     * @type {string}
     * @memberof Topic
     */
    'name': string;
}

