/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Problem } from './problem';
import { TweetComplianceData } from './tweet-compliance-data';
import { TweetComplianceStreamResponseOneOf } from './tweet-compliance-stream-response-one-of';
import { TweetComplianceStreamResponseOneOf1 } from './tweet-compliance-stream-response-one-of1';

/**
 * @type TweetComplianceStreamResponse
 * Tweet compliance stream events.
 * @export
 */
export type TweetComplianceStreamResponse = TweetComplianceStreamResponseOneOf | TweetComplianceStreamResponseOneOf1;


