/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TweetComplianceSchemaTweet } from './tweet-compliance-schema-tweet';

/**
 * 
 * @export
 * @interface TweetNotice
 */
export interface TweetNotice {
    /**
     * If the label is being applied or removed. Possible values are ‘apply’ or ‘remove’.
     * @type {string}
     * @memberof TweetNotice
     */
    'application': string;
    /**
     * Information shown on the Tweet label
     * @type {string}
     * @memberof TweetNotice
     */
    'details'?: string;
    /**
     * Event time.
     * @type {string}
     * @memberof TweetNotice
     */
    'event_at': string;
    /**
     * The type of label on the Tweet
     * @type {string}
     * @memberof TweetNotice
     */
    'event_type': string;
    /**
     * Link to more information about this kind of label
     * @type {string}
     * @memberof TweetNotice
     */
    'extended_details_url'?: string;
    /**
     * Title/header of the Tweet label
     * @type {string}
     * @memberof TweetNotice
     */
    'label_title'?: string;
    /**
     * 
     * @type {TweetComplianceSchemaTweet}
     * @memberof TweetNotice
     */
    'tweet': TweetComplianceSchemaTweet;
}

