/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Organic nonpublic engagement metrics for the Tweet at the time of the request.
 * @export
 * @interface TweetOrganicMetrics
 */
export interface TweetOrganicMetrics {
    /**
     * Number of times this Tweet has been viewed.
     * @type {number}
     * @memberof TweetOrganicMetrics
     */
    'impression_count': number;
    /**
     * Number of times this Tweet has been liked.
     * @type {number}
     * @memberof TweetOrganicMetrics
     */
    'like_count': number;
    /**
     * Number of times this Tweet has been replied to.
     * @type {number}
     * @memberof TweetOrganicMetrics
     */
    'reply_count': number;
    /**
     * Number of times this Tweet has been Retweeted.
     * @type {number}
     * @memberof TweetOrganicMetrics
     */
    'retweet_count': number;
}

