/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Tweet information of the Tweet being replied to.
 * @export
 * @interface TweetCreateRequestReply
 */
export interface TweetCreateRequestReply {
    /**
     * A list of User Ids to be excluded from the reply Tweet.
     * @type {Array<string>}
     * @memberof TweetCreateRequestReply
     */
    'exclude_reply_user_ids'?: Array<string>;
    /**
     * Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
     * @type {string}
     * @memberof TweetCreateRequestReply
     */
    'in_reply_to_tweet_id': string;
}

