/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Point } from './point';

/**
 * The location tagged on the Tweet, if the user provided one.
 * @export
 * @interface TweetGeo
 */
export interface TweetGeo {
    /**
     * 
     * @type {Point}
     * @memberof TweetGeo
     */
    'coordinates'?: Point;
    /**
     * The identifier for this place.
     * @type {string}
     * @memberof TweetGeo
     */
    'place_id'?: string;
}

