/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Media information being attached to created Tweet. This is mutually exclusive from Quote Tweet Id, Poll, and Card URI.
 * @export
 * @interface TweetCreateRequestMedia
 */
export interface TweetCreateRequestMedia {
    /**
     * A list of Media Ids to be attached to a created Tweet.
     * @type {Array<string>}
     * @memberof TweetCreateRequestMedia
     */
    'media_ids': Array<string>;
    /**
     * A list of User Ids to be tagged in the media for created Tweet.
     * @type {Array<string>}
     * @memberof TweetCreateRequestMedia
     */
    'tagged_user_ids'?: Array<string>;
}

