/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TweetLabelData } from './tweet-label-data';

/**
 * Tweet Label event.
 * @export
 * @interface TweetLabelStreamResponseOneOf
 */
export interface TweetLabelStreamResponseOneOf {
    /**
     * 
     * @type {TweetLabelData}
     * @memberof TweetLabelStreamResponseOneOf
     */
    'data': TweetLabelData;
}

