/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TweetNotice } from './tweet-notice';
import { TweetNoticeSchema } from './tweet-notice-schema';
import { TweetUnviewable } from './tweet-unviewable';
import { TweetUnviewableSchema } from './tweet-unviewable-schema';

/**
 * @type TweetLabelData
 * Tweet label data.
 * @export
 */
export type TweetLabelData = TweetNoticeSchema | TweetUnviewableSchema;


