/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TweetEditComplianceObjectSchema } from './tweet-edit-compliance-object-schema';

/**
 * 
 * @export
 * @interface TweetEditComplianceSchema
 */
export interface TweetEditComplianceSchema {
    /**
     * 
     * @type {TweetEditComplianceObjectSchema}
     * @memberof TweetEditComplianceSchema
     */
    'tweet_edit': TweetEditComplianceObjectSchema;
}

