/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TweetCreateRequestGeo } from './tweet-create-request-geo';
import { TweetCreateRequestMedia } from './tweet-create-request-media';
import { TweetCreateRequestPoll } from './tweet-create-request-poll';
import { TweetCreateRequestReply } from './tweet-create-request-reply';

/**
 * 
 * @export
 * @interface TweetCreateRequest
 */
export interface TweetCreateRequest {
    /**
     * Card Uri Parameter. This is mutually exclusive from Quote Tweet Id, Poll, Media, and Direct Message Deep Link.
     * @type {string}
     * @memberof TweetCreateRequest
     */
    'card_uri'?: string;
    /**
     * Link to take the conversation from the public timeline to a private Direct Message.
     * @type {string}
     * @memberof TweetCreateRequest
     */
    'direct_message_deep_link'?: string;
    /**
     * Exclusive Tweet for super followers.
     * @type {boolean}
     * @memberof TweetCreateRequest
     */
    'for_super_followers_only'?: boolean;
    /**
     * 
     * @type {TweetCreateRequestGeo}
     * @memberof TweetCreateRequest
     */
    'geo'?: TweetCreateRequestGeo;
    /**
     * 
     * @type {TweetCreateRequestMedia}
     * @memberof TweetCreateRequest
     */
    'media'?: TweetCreateRequestMedia;
    /**
     * Nullcasted (promoted-only) Tweets do not appear in the public timeline and are not served to followers.
     * @type {boolean}
     * @memberof TweetCreateRequest
     */
    'nullcast'?: boolean;
    /**
     * 
     * @type {TweetCreateRequestPoll}
     * @memberof TweetCreateRequest
     */
    'poll'?: TweetCreateRequestPoll;
    /**
     * Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
     * @type {string}
     * @memberof TweetCreateRequest
     */
    'quote_tweet_id'?: string;
    /**
     * 
     * @type {TweetCreateRequestReply}
     * @memberof TweetCreateRequest
     */
    'reply'?: TweetCreateRequestReply;
    /**
     * Settings to indicate who can reply to the Tweet.
     * @type {string}
     * @memberof TweetCreateRequest
     */
    'reply_settings'?: TweetCreateRequestReplySettingsEnum;
    /**
     * The content of the Tweet.
     * @type {string}
     * @memberof TweetCreateRequest
     */
    'text'?: string;
}

type TweetCreateRequestReplySettingsEnum = 'following' | 'mentionedUsers'


