/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DmEventReferencedTweetsInner } from './dm-event-referenced-tweets-inner';

/**
 * 
 * @export
 * @interface TweetEditComplianceObjectSchema
 */
export interface TweetEditComplianceObjectSchema {
    /**
     * 
     * @type {Array<string>}
     * @memberof TweetEditComplianceObjectSchema
     */
    'edit_tweet_ids': Array<string>;
    /**
     * Event time.
     * @type {string}
     * @memberof TweetEditComplianceObjectSchema
     */
    'event_at': string;
    /**
     * Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
     * @type {string}
     * @memberof TweetEditComplianceObjectSchema
     */
    'initial_tweet_id': string;
    /**
     * 
     * @type {DmEventReferencedTweetsInner}
     * @memberof TweetEditComplianceObjectSchema
     */
    'tweet': DmEventReferencedTweetsInner;
}

