/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TweetReferencedTweetsInner
 */
export interface TweetReferencedTweetsInner {
    /**
     * Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
     * @type {string}
     * @memberof TweetReferencedTweetsInner
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof TweetReferencedTweetsInner
     */
    'type': TweetReferencedTweetsInnerTypeEnum;
}

type TweetReferencedTweetsInnerTypeEnum = 'retweeted' | 'quoted' | 'replied_to'


