/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TweetEditControls
 */
export interface TweetEditControls {
    /**
     * Time when Tweet is no longer editable.
     * @type {string}
     * @memberof TweetEditControls
     */
    'editable_until': string;
    /**
     * Number of times this Tweet can be edited.
     * @type {number}
     * @memberof TweetEditControls
     */
    'edits_remaining': number;
    /**
     * Indicates if this Tweet is eligible to be edited.
     * @type {boolean}
     * @memberof TweetEditControls
     */
    'is_edit_eligible': boolean;
}

