/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TweetComplianceData } from './tweet-compliance-data';

/**
 * Compliance event.
 * @export
 * @interface TweetComplianceStreamResponseOneOf
 */
export interface TweetComplianceStreamResponseOneOf {
    /**
     * 
     * @type {TweetComplianceData}
     * @memberof TweetComplianceStreamResponseOneOf
     */
    'data': TweetComplianceData;
}

