/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Problem } from './problem';
import { TweetDeleteResponseData } from './tweet-delete-response-data';

/**
 * 
 * @export
 * @interface TweetDeleteResponse
 */
export interface TweetDeleteResponse {
    /**
     * 
     * @type {TweetDeleteResponseData}
     * @memberof TweetDeleteResponse
     */
    'data'?: TweetDeleteResponseData;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof TweetDeleteResponse
     */
    'errors'?: Array<Problem>;
}

