/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Place ID being attached to the Tweet for geo location.
 * @export
 * @interface TweetCreateRequestGeo
 */
export interface TweetCreateRequestGeo {
    /**
     * 
     * @type {string}
     * @memberof TweetCreateRequestGeo
     */
    'place_id'?: string;
}

