/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Problem } from './problem';
import { TweetCreateResponseData } from './tweet-create-response-data';

/**
 * 
 * @export
 * @interface TweetCreateResponse
 */
export interface TweetCreateResponse {
    /**
     * 
     * @type {TweetCreateResponseData}
     * @memberof TweetCreateResponse
     */
    'data'?: TweetCreateResponseData;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof TweetCreateResponse
     */
    'errors'?: Array<Problem>;
}

