/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TweetComplianceSchemaTweet } from './tweet-compliance-schema-tweet';

/**
 * 
 * @export
 * @interface TweetComplianceSchema
 */
export interface TweetComplianceSchema {
    /**
     * Event time.
     * @type {string}
     * @memberof TweetComplianceSchema
     */
    'event_at': string;
    /**
     * Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
     * @type {string}
     * @memberof TweetComplianceSchema
     */
    'quote_tweet_id'?: string;
    /**
     * 
     * @type {TweetComplianceSchemaTweet}
     * @memberof TweetComplianceSchema
     */
    'tweet': TweetComplianceSchemaTweet;
}

