/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TweetComplianceSchema } from './tweet-compliance-schema';

/**
 * 
 * @export
 * @interface TweetUndropComplianceSchema
 */
export interface TweetUndropComplianceSchema {
    /**
     * 
     * @type {TweetComplianceSchema}
     * @memberof TweetUndropComplianceSchema
     */
    'undrop': TweetComplianceSchema;
}

