/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TweetComplianceSchema } from './tweet-compliance-schema';
import { TweetDeleteComplianceSchema } from './tweet-delete-compliance-schema';
import { TweetDropComplianceSchema } from './tweet-drop-compliance-schema';
import { TweetEditComplianceObjectSchema } from './tweet-edit-compliance-object-schema';
import { TweetEditComplianceSchema } from './tweet-edit-compliance-schema';
import { TweetTakedownComplianceSchema } from './tweet-takedown-compliance-schema';
import { TweetUndropComplianceSchema } from './tweet-undrop-compliance-schema';
import { TweetWithheldComplianceSchema } from './tweet-withheld-compliance-schema';

/**
 * @type TweetComplianceData
 * Tweet compliance data.
 * @export
 */
export type TweetComplianceData = TweetDeleteComplianceSchema | TweetDropComplianceSchema | TweetEditComplianceSchema | TweetUndropComplianceSchema | TweetWithheldComplianceSchema;


