/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EntityIndicesInclusiveExclusive } from './entity-indices-inclusive-exclusive';
import { UrlFields } from './url-fields';
import { UrlImage } from './url-image';

/**
 * @type UrlEntity
 * Represent the portion of text recognized as a URL, and its start and end position within the text.
 * @export
 */
export type UrlEntity = EntityIndicesInclusiveExclusive & UrlFields;


