/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UrlImage } from './url-image';

/**
 * Represent the portion of text recognized as a URL.
 * @export
 * @interface UrlFields
 */
export interface UrlFields {
    /**
     * Title of the page the URL points to.
     * @type {string}
     * @memberof UrlFields
     */
    'title'?: string;
    /**
     * Description of the URL landing page.
     * @type {string}
     * @memberof UrlFields
     */
    'description'?: string;
    /**
     * The URL as displayed in the Twitter client.
     * @type {string}
     * @memberof UrlFields
     */
    'display_url'?: string;
    /**
     * A validly formatted URL.
     * @type {string}
     * @memberof UrlFields
     */
    'expanded_url'?: string;
    /**
     * 
     * @type {Array<UrlImage>}
     * @memberof UrlFields
     */
    'images'?: Array<UrlImage>;
    /**
     * The Media Key identifier for this attachment.
     * @type {string}
     * @memberof UrlFields
     */
    'media_key'?: string;
    /**
     * HTTP Status Code.
     * @type {number}
     * @memberof UrlFields
     */
    'status'?: number;
    /**
     * Fully resolved url.
     * @type {string}
     * @memberof UrlFields
     */
    'unwound_url'?: string;
    /**
     * A validly formatted URL.
     * @type {string}
     * @memberof UrlFields
     */
    'url': string;
}

