/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Represent the information for the URL image.
 * @export
 * @interface UrlImage
 */
export interface UrlImage {
    /**
     * The height of the media in pixels.
     * @type {number}
     * @memberof UrlImage
     */
    'height'?: number;
    /**
     * A validly formatted URL.
     * @type {string}
     * @memberof UrlImage
     */
    'url'?: string;
    /**
     * The width of the media in pixels.
     * @type {number}
     * @memberof UrlImage
     */
    'width'?: number;
}

