/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Problem } from './problem';
import { UsageCapExceededProblemAllOf } from './usage-cap-exceeded-problem-all-of';

/**
 * @type UsageCapExceededProblem
 * A problem that indicates that a usage cap has been exceeded.
 * @export
 */
export type UsageCapExceededProblem = Problem & UsageCapExceededProblemAllOf;


