/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsageCapExceededProblemAllOf
 */
export interface UsageCapExceededProblemAllOf {
    /**
     * 
     * @type {string}
     * @memberof UsageCapExceededProblemAllOf
     */
    'period'?: UsageCapExceededProblemAllOfPeriodEnum;
    /**
     * 
     * @type {string}
     * @memberof UsageCapExceededProblemAllOf
     */
    'scope'?: UsageCapExceededProblemAllOfScopeEnum;
}

type UsageCapExceededProblemAllOfPeriodEnum = 'Daily' | 'Monthly'
type UsageCapExceededProblemAllOfScopeEnum = 'Account' | 'Product'


