/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserProfileModificationObjectSchema } from './user-profile-modification-object-schema';

/**
 * 
 * @export
 * @interface UserProfileModificationComplianceSchema
 */
export interface UserProfileModificationComplianceSchema {
    /**
     * 
     * @type {UserProfileModificationObjectSchema}
     * @memberof UserProfileModificationComplianceSchema
     */
    'user_profile_modification': UserProfileModificationObjectSchema;
}

