/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Problem } from './problem';
import { UsersRetweetsCreateResponseData } from './users-retweets-create-response-data';

/**
 * 
 * @export
 * @interface UsersRetweetsDeleteResponse
 */
export interface UsersRetweetsDeleteResponse {
    /**
     * 
     * @type {UsersRetweetsCreateResponseData}
     * @memberof UsersRetweetsDeleteResponse
     */
    'data'?: UsersRetweetsCreateResponseData;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof UsersRetweetsDeleteResponse
     */
    'errors'?: Array<Problem>;
}

