/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserComplianceSchema } from './user-compliance-schema';

/**
 * 
 * @export
 * @interface UserUndeleteComplianceSchema
 */
export interface UserUndeleteComplianceSchema {
    /**
     * 
     * @type {UserComplianceSchema}
     * @memberof UserUndeleteComplianceSchema
     */
    'user_undelete': UserComplianceSchema;
}

