/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserComplianceSchemaUser } from './user-compliance-schema-user';

/**
 * 
 * @export
 * @interface UserComplianceSchema
 */
export interface UserComplianceSchema {
    /**
     * Event time.
     * @type {string}
     * @memberof UserComplianceSchema
     */
    'event_at': string;
    /**
     * 
     * @type {UserComplianceSchemaUser}
     * @memberof UserComplianceSchema
     */
    'user': UserComplianceSchemaUser;
}

