/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Problem } from './problem';
import { TweetComplianceStreamResponseOneOf1 } from './tweet-compliance-stream-response-one-of1';
import { UserComplianceData } from './user-compliance-data';
import { UserComplianceStreamResponseOneOf } from './user-compliance-stream-response-one-of';

/**
 * @type UserComplianceStreamResponse
 * User compliance stream events.
 * @export
 */
export type UserComplianceStreamResponse = TweetComplianceStreamResponseOneOf1 | UserComplianceStreamResponseOneOf;


