/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserTakedownComplianceSchema } from './user-takedown-compliance-schema';

/**
 * 
 * @export
 * @interface UserWithheldComplianceSchema
 */
export interface UserWithheldComplianceSchema {
    /**
     * 
     * @type {UserTakedownComplianceSchema}
     * @memberof UserWithheldComplianceSchema
     */
    'user_withheld': UserTakedownComplianceSchema;
}

