/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UrlEntity } from './url-entity';

/**
 * Expanded details for the URL specified in the User\'s profile, with start and end indices.
 * @export
 * @interface UserEntitiesUrl
 */
export interface UserEntitiesUrl {
    /**
     * 
     * @type {Array<UrlEntity>}
     * @memberof UserEntitiesUrl
     */
    'urls'?: Array<UrlEntity>;
}

