/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserEntities } from './user-entities';
import { UserPublicMetrics } from './user-public-metrics';
import { UserWithheld } from './user-withheld';

/**
 * The Twitter User object.
 * @export
 * @interface User
 */
export interface User {
    /**
     * The text of this User\'s profile description (also known as bio), if the User provided one.
     * @type {string}
     * @memberof User
     */
    'description'?: string;
    /**
     * Creation time of this User.
     * @type {string}
     * @memberof User
     */
    'created_at'?: string;
    /**
     * 
     * @type {UserEntities}
     * @memberof User
     */
    'entities'?: UserEntities;
    /**
     * Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
     * @type {string}
     * @memberof User
     */
    'id': string;
    /**
     * The location specified in the User\'s profile, if the User provided one. As this is a freeform value, it may not indicate a valid location, but it may be fuzzily evaluated when performing searches with location queries.
     * @type {string}
     * @memberof User
     */
    'location'?: string;
    /**
     * The friendly name of this User, as shown on their profile.
     * @type {string}
     * @memberof User
     */
    'name': string;
    /**
     * Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
     * @type {string}
     * @memberof User
     */
    'pinned_tweet_id'?: string;
    /**
     * The URL to the profile image for this User.
     * @type {string}
     * @memberof User
     */
    'profile_image_url'?: string;
    /**
     * Indicates if this User has chosen to protect their Tweets (in other words, if this User\'s Tweets are private).
     * @type {boolean}
     * @memberof User
     */
    'protected'?: boolean;
    /**
     * 
     * @type {UserPublicMetrics}
     * @memberof User
     */
    'public_metrics'?: UserPublicMetrics;
    /**
     * The URL specified in the User\'s profile.
     * @type {string}
     * @memberof User
     */
    'url'?: string;
    /**
     * The Twitter handle (screen name) of this user.
     * @type {string}
     * @memberof User
     */
    'username': string;
    /**
     * Indicate if this User is a verified Twitter User.
     * @type {boolean}
     * @memberof User
     */
    'verified'?: boolean;
    /**
     * The Twitter Blue verified type of the user, eg: blue, government, business or none.
     * @type {string}
     * @memberof User
     */
    'verified_type'?: string;
    /**
     * 
     * @type {UserWithheld}
     * @memberof User
     */
    'withheld'?: UserWithheld;
}

