/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserComplianceSchema } from './user-compliance-schema';
import { UserDeleteComplianceSchema } from './user-delete-compliance-schema';
import { UserProfileModificationComplianceSchema } from './user-profile-modification-compliance-schema';
import { UserProfileModificationObjectSchema } from './user-profile-modification-object-schema';
import { UserProtectComplianceSchema } from './user-protect-compliance-schema';
import { UserScrubGeoObjectSchema } from './user-scrub-geo-object-schema';
import { UserScrubGeoSchema } from './user-scrub-geo-schema';
import { UserSuspendComplianceSchema } from './user-suspend-compliance-schema';
import { UserTakedownComplianceSchema } from './user-takedown-compliance-schema';
import { UserUndeleteComplianceSchema } from './user-undelete-compliance-schema';
import { UserUnprotectComplianceSchema } from './user-unprotect-compliance-schema';
import { UserUnsuspendComplianceSchema } from './user-unsuspend-compliance-schema';
import { UserWithheldComplianceSchema } from './user-withheld-compliance-schema';

/**
 * @type UserComplianceData
 * User compliance data.
 * @export
 */
export type UserComplianceData = UserDeleteComplianceSchema | UserProfileModificationComplianceSchema | UserProtectComplianceSchema | UserScrubGeoSchema | UserSuspendComplianceSchema | UserUndeleteComplianceSchema | UserUnprotectComplianceSchema | UserUnsuspendComplianceSchema | UserWithheldComplianceSchema;


