/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A list of metrics for this User.
 * @export
 * @interface UserPublicMetrics
 */
export interface UserPublicMetrics {
    /**
     * Number of Users who are following this User.
     * @type {number}
     * @memberof UserPublicMetrics
     */
    'followers_count': number;
    /**
     * Number of Users this User is following.
     * @type {number}
     * @memberof UserPublicMetrics
     */
    'following_count': number;
    /**
     * The number of lists that include this User.
     * @type {number}
     * @memberof UserPublicMetrics
     */
    'listed_count': number;
    /**
     * The number of Tweets (including Retweets) posted by this User.
     * @type {number}
     * @memberof UserPublicMetrics
     */
    'tweet_count': number;
}

