/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Variant
 */
export interface Variant {
    /**
     * The bit rate of the media.
     * @type {number}
     * @memberof Variant
     */
    'bit_rate'?: number;
    /**
     * The content type of the media.
     * @type {string}
     * @memberof Variant
     */
    'content_type'?: string;
    /**
     * The url to the media.
     * @type {string}
     * @memberof Variant
     */
    'url'?: string;
}

