/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Media } from './media';
import { Variant } from './variant';
import { VideoAllOf } from './video-all-of';
import { VideoAllOfNonPublicMetrics } from './video-all-of-non-public-metrics';
import { VideoAllOfOrganicMetrics } from './video-all-of-organic-metrics';
import { VideoAllOfPromotedMetrics } from './video-all-of-promoted-metrics';
import { VideoAllOfPublicMetrics } from './video-all-of-public-metrics';

/**
 * @type Video
 * @export
 */
export type Video = Media & VideoAllOf;


