/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Variant } from './variant';
import { VideoAllOfNonPublicMetrics } from './video-all-of-non-public-metrics';
import { VideoAllOfOrganicMetrics } from './video-all-of-organic-metrics';
import { VideoAllOfPromotedMetrics } from './video-all-of-promoted-metrics';
import { VideoAllOfPublicMetrics } from './video-all-of-public-metrics';

/**
 * 
 * @export
 * @interface VideoAllOf
 */
export interface VideoAllOf {
    /**
     * 
     * @type {number}
     * @memberof VideoAllOf
     */
    'duration_ms'?: number;
    /**
     * 
     * @type {VideoAllOfNonPublicMetrics}
     * @memberof VideoAllOf
     */
    'non_public_metrics'?: VideoAllOfNonPublicMetrics;
    /**
     * 
     * @type {VideoAllOfOrganicMetrics}
     * @memberof VideoAllOf
     */
    'organic_metrics'?: VideoAllOfOrganicMetrics;
    /**
     * 
     * @type {string}
     * @memberof VideoAllOf
     */
    'preview_image_url'?: string;
    /**
     * 
     * @type {VideoAllOfPromotedMetrics}
     * @memberof VideoAllOf
     */
    'promoted_metrics'?: VideoAllOfPromotedMetrics;
    /**
     * 
     * @type {VideoAllOfPublicMetrics}
     * @memberof VideoAllOf
     */
    'public_metrics'?: VideoAllOfPublicMetrics;
    /**
     * An array of all available variants of the media.
     * @type {Array<Variant>}
     * @memberof VideoAllOf
     */
    'variants'?: Array<Variant>;
}

