/*
Twitter API v2

Twitter API v2 available endpoints

The version of the OpenAPI document: 2.62


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Promoted nonpublic engagement metrics for the Media at the time of the request.
 * @export
 * @interface VideoAllOfPromotedMetrics
 */
export interface VideoAllOfPromotedMetrics {
    /**
     * Number of users who made it through 0% of the video.
     * @type {number}
     * @memberof VideoAllOfPromotedMetrics
     */
    'playback_0_count'?: number;
    /**
     * Number of users who made it through 100% of the video.
     * @type {number}
     * @memberof VideoAllOfPromotedMetrics
     */
    'playback_100_count'?: number;
    /**
     * Number of users who made it through 25% of the video.
     * @type {number}
     * @memberof VideoAllOfPromotedMetrics
     */
    'playback_25_count'?: number;
    /**
     * Number of users who made it through 50% of the video.
     * @type {number}
     * @memberof VideoAllOfPromotedMetrics
     */
    'playback_50_count'?: number;
    /**
     * Number of users who made it through 75% of the video.
     * @type {number}
     * @memberof VideoAllOfPromotedMetrics
     */
    'playback_75_count'?: number;
    /**
     * Number of times this video has been viewed.
     * @type {number}
     * @memberof VideoAllOfPromotedMetrics
     */
    'view_count'?: number;
}

